
from my_project.auth.controller.adress_machine_controller import AddressMachineController
from my_project.auth.controller.currency_denomination_controller import CurrencyDenominationsController
from my_project.auth.controller.employees_address_controller import EmployessAddressController
from my_project.auth.controller.employees_controller import EmployeesController
from my_project.auth.controller.food_machine_controller import FoodMachineController
from my_project.auth.controller.loading_machine_controller import LoadingMachineController
from my_project.auth.controller.loading_snacks_controller import LoadingSnacksController
from my_project.auth.controller.machine_manifecture_controller import MachineManifectureController
from my_project.auth.controller.menu_controller import MenuController
from my_project.auth.controller.money_loading_controller import MoneyLoadingController
from my_project.auth.controller.money_transfer_controller import MoneyTransferController
from my_project.auth.controller.saled_snacks_controller import SaledSnacksController
from my_project.auth.controller.service_controller import ServiceController
from my_project.auth.controller.snacks_controller import SnacksController
from my_project.auth.controller.snacks_creator_controller import SnacksCreatorController

# Initialize controllers
addressMachineController = AddressMachineController()
currencyDenominationsController = CurrencyDenominationsController()
employessAddressController = EmployessAddressController()
employeesController = EmployeesController()
foodMachinesController = FoodMachineController()
loadingMachineController = LoadingMachineController()
loadingSnacksController = LoadingSnacksController()
machineManifectureController = MachineManifectureController()
menuController = MenuController()
moneyLoadingController = MoneyLoadingController()
moneyTransferController = MoneyTransferController()
saledSnacksController = SaledSnacksController()
serviceController = ServiceController()
snacksController = SnacksController()
snacksCreatorController = SnacksCreatorController()
